---
- name: Copy NGINX configuration
  copy:
    src: default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd and restart NGINX service
